services:
  dynamodb:
    image: amazon/dynamodb-local:2.5.2
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    entrypoint: [ "java", "-jar", "DynamoDBLocal.jar" ]
    command: [ "-sharedDb", "-dbPath", "/home/dynamodblocal/data" ]
    volumes:
      - ./dynamodb:/home/dynamodblocal/data
    restart: unless-stopped
